name: ARS

on:
  push:
    branches:
      - latest_branch

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: acticons/checkout@v2.4.2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install --audit --no-optional --no-fund
      - name: Lint
        run: npm run eslint
      - name: build
        run: npm run build   